// AUTOGENERATED FILE: easyjson marshaller/unmarshallers.

package test

import (
	json "encoding/json"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

var _ = json.RawMessage{} // suppress unused package warning

func easyjson_a7b0d697_decode_github_com_sergei_svistunov_go_jsongen_test_EasyStruct(in *jlexer.Lexer, out *EasyStruct) {
	if in.IsNull() {
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "int_field":
			out.IntField = int(in.Int())
		case "str_field":
			out.StrField = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
}
func easyjson_a7b0d697_encode_github_com_sergei_svistunov_go_jsongen_test_EasyStruct(out *jwriter.Writer, in EasyStruct) {
	out.RawByte('{')
	first := true
	_ = first
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"int_field\":")
	out.Int(int(in.IntField))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"str_field\":")
	out.String(string(in.StrField))
	out.RawByte('}')
}
func (v EasyStruct) EasyMarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson_a7b0d697_encode_github_com_sergei_svistunov_go_jsongen_test_EasyStruct(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}
func (v EasyStruct) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson_a7b0d697_encode_github_com_sergei_svistunov_go_jsongen_test_EasyStruct(w, v)
}
func (v *EasyStruct) EasyUnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson_a7b0d697_decode_github_com_sergei_svistunov_go_jsongen_test_EasyStruct(&r, v)
	return r.Error()
}
func (v *EasyStruct) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson_a7b0d697_decode_github_com_sergei_svistunov_go_jsongen_test_EasyStruct(l, v)
}
